version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hugo-network

  server:
    build: 
      context: .
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - hugo-network

volumes:
  redis-data:
   
networks:
  hugo-network:
    driver: bridge